# Generated by Django 4.2.11 on 2024-05-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="get_posts",
                to="core.author",
                verbose_name="Autor",
            ),
        ),
    ]
