# Generated by Django 4.2.11 on 2024-05-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_post_dislike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="dislike",
            new_name="dislikes",
        ),
    ]
